### ISSUE TITLE
highlight the text 

### ISSUE THREAD

**Issue by JanRegent** [aashish2604/parsed_readmore#1]
Can you add a parameter to highlight the text string?

Thanks a lot

**Comment by aashish2604** [comment]
> Can you add a parameter to highlight the text string?
> 
> Thanks a lot
You can provide custom text styles to both the plain text and the urls. What addition highlighting do you need exactly? It will be very helpful if you send some sort of example in my email.

**Comment by JanRegent** [comment]
solved in 0.0,6

**Comment by JanRegent** [comment]
thanks
